import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { getApiEndpoint as getApiEndpoint } from "@/lib/config";
import { ShowBrowserApiEndpoint } from "@/components/ShowBroswerApiEndpoint";
import { GetServerSideProps } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

interface HomeProps {
  apiEndpoint?: string;
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  return {
    props: {
      apiEndpoint: getApiEndpoint(),
    },
  };
};

export default function Home({
  apiEndpoint, // This will be used if needed in the future
}: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <ul>
            <li>
              <code>API_ENDPOINT</code> is set to:{" "}
              <span className={styles.apiEndpoint}>{apiEndpoint}</span>
            </li>
          </ul>
          <ShowBrowserApiEndpoint />
        </main>
      </div>
    </>
  );
}
